version: '3'
services:
  server:
    container_name: nebo
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../../src:/usr/src/app/src
      - ../../core:/usr/src/app/core
      - ../../config:/usr/src/app/config
      - ../../test:/usr/src/app/test
    ports:
      - '8112:8112'
