version: '3'
services:
  server:
    container_name: nebo
    build: ./
    volumes:
      - ./src:/usr/src/app/src
      - ./core:/usr/src/app/core
      - ./config:/usr/src/app/config
      - ./test:/usr/src/app/test
    ports:
      - '8112:8112'

  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=nebo
      - POSTGRES_PASSWORD=123
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
