version: '3'
services:
  server:
    container_name: station-backend
    platform: linux/amd64
    image: boy672820/station-backend
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    volumes:
      - ../../src:/usr/src/app/src
      - ../../core:/usr/src/app/core
      - ../../config:/usr/src/app/config
      - ../../test:/usr/src/app/test
    ports:
      - '8112:8112'
